[General]
# Palette injected from theme/colors.env at apply time. Main.qml reads
# these via config.<key>. Hex values keep the leading '#'.

ColorBase      =#@BG@
ColorMantle    =#@BG_ALT@
ColorCrust     =#@BG_DEEP@
ColorSurface0  =#@SURFACE0@
ColorSurface1  =#@SURFACE1@
ColorText      =#@FG@
ColorSubtext   =#@FG_DIM@
ColorOverlay   =#@MUTED@
ColorAccent    =#@ACCENT@
ColorAccentFg  =#@BG_DEEP@
ColorError     =#@ERROR@

Font           =JetBrainsMono Nerd Font
FontSize       =11

# Pre-blurred wallpaper generated by apply.sh's ensure_sddm_theme.
# Defining it also silences SDDM's "no Background property" warning.
Background     =background.png

